apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: przychodnia-app
spec:
  type: LoadBalancer
  selector:
    app: przychodnia-app
  ports:
    - protocol: TCP
      port: 80              # Użytkownik wchodzi przez port 80 (standard HTTP)
      targetPort: 8000      # Aplikacja działa wewnętrznie na porcie 8000
