# Generated by Django 3.2.15 on 2025-01-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pesel',
            field=models.CharField(max_length=11, null=True, verbose_name='PESEL'),
        ),
    ]
