# Generated by Django 3.2.15 on 2025-01-04 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_examination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0003_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='medicines',
            new_name='medications',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='pesel',
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='main.doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
