"""
Django settings for przychodnia_app project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-msq!_v8la8ma5agy#(aocy(9@p7vhpa$$&7*p+mng8asxex(^6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_recaptcha',
    'main.apps.MainConfig',
    'accounts',
    'appointment',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'przychodnia_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'przychodnia_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'Przychodnia',
        'USER': 'postgres',
        'PASSWORD': 'admin',
        'PORT': '5432',
        'HOST': 'localhost',

    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'staticfiles/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [BASE_DIR / 'static' ,]

# django_project/settings.py
LOGIN_REDIRECT_URL = "home"  
LOGOUT_REDIRECT_URL = "home"

# e-mail configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com' 
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'prybka2@gmail.com'
EMAIL_HOST_PASSWORD = 'gwsl theu thvd nnkd' 

# captcha configuration
RECAPTCHA_PUBLIC_KEY = '6Lf3BK0qAAAAAKfc9ox5x3NR-fL4cJBvIH64JXGa'
RECAPTCHA_PRIVATE_KEY = '6Lf3BK0qAAAAAHHwxfrVaoZw5cYCN8EpUWlexFZ9'

# security https configuration

# WHILE WORKING LOCALY DJANGO DOESN"T SUPPORT HTTPS, TO ALLOW HTTPS CHANGE FIRST THREE TO TRUE 

# Enforce HTTPS redirection
SECURE_SSL_REDIRECT = False 
# Ensure session cookies are only sent over HTTPS
SESSION_COOKIE_SECURE = False  
# Require CSRF cookies to be transmitted only over HTTPS
CSRF_COOKIE_SECURE = False  
# Enable HTTP Strict Transport Security (HSTS) for 1 year
SECURE_HSTS_SECONDS = 31536000  
# Apply HSTS to all subdomains
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  
# Allow the domain to be preloaded in browser HSTS lists
SECURE_HSTS_PRELOAD = True  
# Enable the browser's built-in XSS protection
SECURE_BROWSER_XSS_FILTER = True  
# Prevent the browser from interpreting files as a different MIME type
SECURE_CONTENT_TYPE_NOSNIFF = True  

